# AI Applications & Mini Project 5 — AI assistants and project planning

**Digital Foundation for Chemical Engineers**  \nDuration: 60 minutes

## Today’s goal
Use a CSV case study to define a modest, useful AI/analytics project; learn how AI assistants can support work while keeping people responsible for facts, calculations, and decisions.

## 1. What AI assistants can and cannot do (10 min)

AI assistants can help explain code, suggest data checks, draft report wording, brainstorm features, and improve presentation structure. They can also make mistakes, invent sources, expose confidential data if used carelessly, or give overconfident advice.

Rules for responsible use: do not paste confidential plant data into unapproved tools; verify claims and calculations; state when AI assisted work; retain human ownership of engineering judgement.

In [3]:
import pandas as pd
link = 'https://raw.githubusercontent.com/Khushi-chan/Module_5_6_Both/refs/heads/main/05_05_ai_assistants_project_planning.ipynb'

# Load the dataset directly from the online repository
data_url = 'https://raw.githubusercontent.com/Khushi-chan/Module_5_6_Both/refs/heads/main/data/quality_batches_120.csv'
case_data = pd.read_csv(data_url)
case_data['timestamp'] = pd.to_datetime(case_data['timestamp'])
case_data.head()

,timestamp,batch_id,reactor,inlet_temperature_c,conversion_percent,product_purity_percent,lab_result
0,2026-02-02 08:00:00,Q2001,R1,72.0,88.5,96.20,REVIEW
1,2026-02-02 09:00:00,Q2001,R2,72.6,88.5,96.39,REVIEW
2,2026-02-02 10:00:00,Q2001,R3,73.2,89.0,96.58,REVIEW
3,2026-02-02 11:00:00,Q2001,R1,73.8,89.9,96.77,REVIEW
4,2026-02-02 12:00:00,Q2001,R2,74.4,89.9,96.96,REVIEW

In [9]:
# filter batches by lab result

#count PASS and REVIEW batches
pass_batches = case_data[case_data['lab_result'] == 'PASS']
review_batches = case_data[case_data['lab_result'] == 'REVIEW']

In [10]:
# Count and display the number of PASS and REVIEW batches
pass_count = len(pass_batches)
review_count = len(review_batches)

print(f"Number of PASS batches: {pass_count}")
print(f"Number of REVIEW batches: {review_count}")

Number of PASS batches: 77
Number of REVIEW batches: 43

## 2. Frame a project question (12 min)
A good student project is narrow, measurable, and tied to a user.

Example: Use historic batch data to identify records that may require quality review.

Define user, decision supported, CSV source, target/outcome, input features, success measure, limits, and required human review. Avoid claiming that a short classroom dataset can validate a production AI system.

In [11]:
project_snapshot = case_data.groupby('lab_result').agg(
    records=('batch_id', 'count'),
    mean_conversion=('conversion_percent', 'mean'),
    mean_purity=('product_purity_percent', 'mean')
)
display(project_snapshot.round(2))
print('Potential input features:', ['inlet_temperature_c', 'conversion_percent', 'reactor'])
print('Potential outcome label: lab_result')

            records  mean_conversion  mean_purity
lab_result
PASS             77            92.37        97.08
REVIEW           43            89.09        96.98

Potential input features: ['inlet_temperature_c', 'conversion_percent', 'reactor']
Potential outcome label: lab_result

**Try it (4 min):** State one question this CSV can answer and one important question it cannot answer.

**Challenge:** Identify one possible bias or limitation in using lab_result as the target label.

## 3. Prompting an AI assistant responsibly (12 min)
A useful request gives context, desired output, constraints, and a verification step. Example prompt: I have a CSV with batch-quality columns. Suggest three data-quality checks in pandas. Do not invent results; explain how I can verify each check.

Use only non-confidential or approved data. Run suggested code yourself and inspect results. Treat suggested code as a draft requiring review.

## 4. Project canvas (15 min)
Complete the following:

1. Title and stakeholder
2. Decision/problem supported
3. Input CSV and columns used
4. One analysis or screening method
5. Visual/report output
6. Limitation and human-review step

Your result may be a strong analysis/automation project; it does not need to be a trained ML model to be valuable.

In [12]:
project_columns = case_data[['timestamp', 'reactor', 'inlet_temperature_c',
                             'conversion_percent', 'product_purity_percent', 'lab_result']]
project_columns.head()

,timestamp,reactor,inlet_temperature_c,conversion_percent,product_purity_percent,lab_result
0,2026-02-02 08:00:00,R1,72.0,88.5,96.20,REVIEW
1,2026-02-02 09:00:00,R2,72.6,88.5,96.39,REVIEW
2,2026-02-02 10:00:00,R3,73.2,89.0,96.58,REVIEW
3,2026-02-02 11:00:00,R1,73.8,89.9,96.77,REVIEW
4,2026-02-02 12:00:00,R2,74.4,89.9,96.96,REVIEW

## Exit check
You can frame a manageable project and use AI assistants as reviewed collaborators rather than unquestioned authorities. Next hour: build and present the mini project.